# Assignment

In [1]:
#IN this i am using a list of lists reppresenting the board where cells are supposed to be evolve.


import numpy as np
A=np.array( [[0,0,0,0,0,1],
     [0,0,0,1,0,0],
     [0,1,0,1,0,0],
     [0,0,1,1,0,0],
     [0,0,0,0,0,0],
     [1,0,0,0,0,0]])

def neighbours(A):     
    s=len(A),len(A[0])
    Z=[[0,]*(s[0])  for x in range(s[1])]
    for u in range(1,s[0]-1):
        for v in range(1,s[1]-1):
            Z[u][v]=A[u-1][v-1]+A[u][v-1]+A[u+1][v-1]\
                    + A[u-1][v]+A[u+1][v]\
                    + A[u-1][v+1]+A[u][v+1]+A[u+1][v+1]
    return Z

def result(A):
    for y in A[1:-1]:
        print(y[1:-1])
    print()

def generate(A):
    s=len(A), len(A[0])
    Z=neighbours(A)
    for u in range(1,s[0]-1):
        for v in range(1,s[1]-1):
            if A[u][v]==1 and (Z[u][v]<2 or Z[u][v]>3):
                A[u][v]=0
            elif A[u][v]==0 and Z[u][v]==3:
                A[u][v]=1
    return A

result(A)
for x in range(3):
    generate(A)
result(A)

[0 0 1 0]
[1 0 1 0]
[0 1 1 0]
[0 0 0 0]

[0 0 0 1]
[0 0 0 1]
[0 0 1 1]
[0 0 1 0]

